### ISSUE TITLE
Ardour feedback

### ISSUE THREAD

**Issue by ovenwerks** [onkelDead/ardmix#1]
I was not sure how else to contact you, sorry. I am letting you know that the way /strip/list works has changed in recent git.
Ardour now sends /strip/list to the surface if there are strip deletions/additions/order changes so the surface can update it list of strips. the  /strip/list command now gets VCAs listed as well. see:
http://manual.ardour.org/using-control-surfaces/controlling-ardour-with-osc/querying-ardour-with-osc/

I have tried to make the changes in such a way that a surface should be able to work with the old or new way. It should be possible to support Ardour 5.0 and up... or at least Ardour 5.whenever you added plugin things and up :)

**Comment by onkelDead** [comment]
I've checked all functions regarding new Ardour OSC behavior.
Changes are applied in current version.
