### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by x42** [onkelDead/ardmix#3]
Under what license conditions can one use and modify ardmix?

**Comment by onkelDead** [comment]
I didn't thought about that, but feel free to use/modify it as you want.

**Comment by ohli** [comment]
Thanks for the freedom and trust in the users!
I'm thinking about adding your app to [f-droid,](https://f-droid.org/de/docs/Inclusion_Policy/) but it won't be possible without a license (sounds quite bureaucratic), You may check: 
https://www.gnu.org/licenses/license-list.html

**Comment by x42** [comment]
my personal license choice is either [GPL](https://en.wikipedia.org/wiki/GNU_General_Public_License) or [MIT](https://en.wikipedia.org/wiki/MIT_License)/[ISC](https://en.wikipedia.org/wiki/ISC_license).  The GPL for end-user products to provide freedom to the user.  The latter for infrastructure projects (libs, etc) where the interface and interoperability is more important (provide freedom to developers, incl non-free projects).

If you truly don't care, there's always http://www.wtfpl.net/  :)

**Comment by onkelDead** [comment]
Cheers!
