### ISSUE TITLE
exactly what I am after!

### ISSUE THREAD

**Issue by Knollewurz** [onkelDead/ardmix#6]
Ahoil, 

looks awesome, but how do i get this on my device?
it screams "parsingerror". 
may i suggest f-droid?

**Comment by agittins** [comment]
Howdy!

I'm not sure that this project is being actively maintained, I wasn't able to get it working reliably for me (had to build it myself, and lots of stuff didn't work).

I hope this isn't uncool to do here, but I had excellent success using [OpenStageControl](https://openstagecontrol.ammd.net/), using its built-in ardour template, which works really well.

I launch it using (note your paths will be different):

`open-stage-control -- -l ~/src/open-stage-control/ardour-control/ardour.json -c ~/src/open-stage-control/ardour-control/ardour-plugins-module.js -s 127.0.0.1:3819`

You run this on your machine running Ardour, then on your android (or anything) device you open a web browser and point it at http://ardour-machines-address:8080/ - make sure you press the "connect" button on the "settings" page, then it will load all the track names etc for the "mixer" tab.

**Comment by onkelDead** [comment]
closed intenionally
